apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-date-ip
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cron
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cron
            image: curlimages/curl
            command: ["/bin/sh", "-c", 
            "date; curl -s ipinfo.io/ip"]
